# Generated by Django 5.0 on 2024-01-03 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_profile_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'user profile', 'verbose_name_plural': 'users profiles'},
        ),
    ]
