# Generated by Django 5.0 on 2024-01-05 16:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_userprofile_updated_at_alter_userprofile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttag',
            name='updated_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Data de atualização'),
        ),
        migrations.AlterField(
            model_name='posttag',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='posttag',
            name='slug',
            field=models.SlugField(max_length=60, unique=True),
        ),
    ]
