# Generated by Django 5.0 on 2024-01-06 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='likes counter'),
        ),
        migrations.AlterField(
            model_name='post',
            name='public_id',
            field=models.CharField(max_length=14, unique=True, verbose_name='ID used for public posts URL'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='posttag',
            name='updated_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
