# Generated by Django 5.0 on 2024-01-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_post_likes_alter_post_public_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers_counter',
            field=models.PositiveIntegerField(default=0, verbose_name='followers counter'),
        ),
    ]
