# Generated by Django 5.0 on 2024-01-07 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_user_followers_counter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='likes_counter',
        ),
    ]
