# Generated by Django 5.0 on 2024-01-07 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_postlike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postlike',
            options={'verbose_name': 'post like', 'verbose_name_plural': 'posts likes'},
        ),
    ]
