# Generated by Django 5.0 on 2024-01-08 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_user_followers_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes_counter',
        ),
    ]
